### ISSUE TITLE
Cache files are not being removed in current pub release

### ISSUE THREAD

**Issue by js2702** [Baseflow/flutter_cache_manager#476]
## 🐛 Bug Report

The recent bug fix in the commit #469 does actually fix a serious bug which has been in the library for two years where the cache files are neved cleaned up because the `file.exists()` doesn't point to the correct file. The fix has been merged but the release in pub.dev is missing.

There are several issues about this behaviour that have been reported for quite some time.

#377, #452, #446 

@mvanbeusekom Sorry for the ping but I believe this is a serious fix missing.

**Comment by escamoteur** [comment]
Could you please push a new release? Our users reported cache sized of 30GB in some cases

**Comment by suli1** [comment]
Any update ?

**Comment by mikefaust-jm** [comment]
For the time being pin the version in your pubspec.yaml to the current git commit:
```yaml
  flutter_cache_manager:
    git:
      url: https://github.com/Baseflow/flutter_cache_manager.git
      path: flutter_cache_manager
      ref: "54904e4"
```
